//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3CX.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3CX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        internal static System.Drawing.Icon _3cx {
            get {
                object obj = ResourceManager.GetObject("_3cx", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3CX_FULL {
            get {
                object obj = ResourceManager.GetObject("_3CX_FULL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3cx1 {
            get {
                object obj = ResourceManager.GetObject("_3cx1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FirstName;LastName;Company;Mobile;Mobile2;Home;Home2;Business;Business2;Email;Other;BusinessFax;HomeFax;Pager;
        ///.
        /// </summary>
        internal static string cellaUscitaContatti {
            get {
                return ResourceManager.GetString("cellaUscitaContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome;Cognome;mail;Numero 1;Numero 2;Numero 3;Numero 4;Numero 5;Numero 6
        ///.
        /// </summary>
        internal static string celleContatti {
            get {
                return ResourceManager.GetString("celleContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Impostazione;IP Centralino;IP SBC;VLAN Tel;VLAN PC;Nome Template 3CX;XML;
        ///Yealink T2X-3X-4X;;;;;yealinkT4x.ph.xml;&lt;PhoneDevice ProvType=&quot;0&quot; PhoneLanguage=&quot;Italian&quot; XferType=&quot;AttXfer&quot; RingTone=&quot;Ring 1&quot; DateFormat=&quot;DD MMM YYYY (15 Jan 2017)&quot; TimeFormat=&quot;24-hour clock&quot; PowerLed=&quot;No Power LED notifications&quot; Backlight=&quot;1 minute&quot; ScreenSaver=&quot;5 minutes&quot;&gt;&lt;CustomQueueRingTones /&gt;&lt;mcgroups enabled=&quot;false&quot; /&gt;&lt;DynamicOptions&gt;&lt;option name=&quot;vlanwanport&quot; value=&quot;False&quot; /&gt;&lt;option name=&quot;vlanwanid&quot; value=&quot;1&quot; /&gt;&lt;option  [stringa troncata]&quot;;.
        /// </summary>
        internal static string celleImpostazioni {
            get {
                return ResourceManager.GetString("celleImpostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Interno;Nome;Cognome;Email;Numero Cell;Numero Uscita;Telefono;MAC;Riga Impostazioni
        ///.
        /// </summary>
        internal static string celleInterni {
            get {
                return ResourceManager.GetString("celleInterni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number;FirstName;LastName;EmailAddress;MobileNumber;AuthID;AuthPassword;WebMeetingFriendlyName;WebMeetingPrivateRoom;ClickToCall;ClickToCallFriendlyName;WebMeetingAcceptReject;EnableVoicemail;VMNoPin;VMPlayCallerID;PIN;VMPlayMsgDateTime;VMEmailOptions;QueueStatus;OutboundCallerID;SIPID;DeliverAudio;SupportReinvite;SupportReplaces;EnableSRTP;ManagementAccess;ReporterAccess;WallboardAccess;TurnOffMyPhone;HideFWrules;CanSeeRecordings;CanDeleteRecordings;RecordCalls;CallScreening;EmailMissedCalls;Disabled;Disab [stringa troncata]&quot;;.
        /// </summary>
        internal static string celleUscitaInterni {
            get {
                return ResourceManager.GetString("celleUscitaInterni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_filled {
            get {
                object obj = ResourceManager.GetObject("logo_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
